class Main
    function main () void do
        declare int i;
        declare String output;
        set i = 1;

        while i < 16 do
            set output = "";

            if i % 3 = 0 do
                set output = String.concat(output, "Fizz");
            end

            if i % 5 = 0 do
                set output = String.concat(output, "Buzz");
            end

            set i = i + 1;
        end
    end
end